services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: nutri
      POSTGRES_PASSWORD: nutri
      POSTGRES_DB: nutri
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: